#!/bin/sh
# @(#) Find a median value from text like seq(1). Version 1.0.0.20131021

PATH=/bin:/usr/bin:/usr/local/bin

readonly progname=`basename "$0"`

# do_exit <status>
do_exit() {
    rm -f "$tmpfile"
    exit $1
}

# usage <status>
usage() {
    echo "usage: $progname [-h] [file ...]" 1>&2
    exit $1
}

opt=
while getopts 'h' opt; do
    case $opt in
    h)      usage 0 ;;
    \?)     usage 1 ;;
    esac
done
shift `expr $OPTIND - 1`

trap 'rm -f "$tmpfile"; exit 1' 1 2 15

tmpfile=`mktemp "$progname.$$.XXXXXXXXXX"`
if [ $? -ne 0 ]; then
    echo "$progname: cannot create temporary file" 1>&2
    exit 1
fi

nsamples=`sort -n ${@+"$@"} | tee "$tmpfile" | wc -l`
[ "$nsamples" -gt 0 ] || do_exit 0

mid=`expr $nsamples / 2`
if [ `expr $nsamples % 2` = 1 ]; then
    sed -n "`expr $mid + 1`p" "$tmpfile"
else
    sed -n "$mid,`expr $mid + 1`p" "$tmpfile" |
    paste -d '+' -s |
    sed 's%^.*$%scale = 16; (&) / 2%' |
    bc -q -s
fi

rm -f "$tmpfile"
