#!/bin/sh
# @(#) Calculate standard deviation from text like seq(1). Version 1.0.0.20131020

readonly progname=`basename "$0"`

# do_exit <status>
do_exit() {
    rm -f "$tmpfile"
    exit $1
}

# usage <status>
usage() {
    echo "usage: $progname [-h] [file ...]" 1>&2
    exit $1
}

opt=
while getopts 'h' opt; do
    case $opt in
    h)      usage 0 ;;
    \?)     usage 1 ;;
    esac
done
shift `expr $OPTIND - 1`

trap 'rm -f "$tmpfile"; exit 1' 1 2 15

tmpfile=`mktemp "$progname.$$.XXXXXXXXXX"`
if [ $? -ne 0 ]; then
    echo "$progname: cannot create temporary file" 1>&2
    exit 1
fi

cat ${@+"$@"} >"$tmpfile"
{
sed '
1i\
scale = 16\
t = 0\
n = 0
s/^.*$/t += &; n++/
$a\
m = t / n' "$tmpfile"

sed '
1i\
t = 0
s/^.*$/t += (& - m) ^ 2/
$a\
sqrt(t / n)' "$tmpfile"
} | bc -q -s | tail -1

rm -f "$tmpfile"
