#!/bin/sh
# @(#) Calculate arithmetic mean from text like seq(1). Version 1.0.0.20131020

# usage <status>
usage() {
    echo "usage: `basename "$0"` [-h] [file ...]" 1>&2
    exit $1
}

opt=
while getopts 'h' opt; do
    case $opt in
    h)      usage 0 ;;
    \?)     usage 1 ;;
    esac
done
shift `expr $OPTIND - 1`

exec sed '
1i\
scale = 16\
t = 0\
n = 0
s/^.*$/t += &; n++/
$a\
t / n' ${@+"$@"} | bc -q -s | tail -1
