#!/bin/sh
# @(#) Find mode values from text like seq(1). Version 1.0.0.20131021

PATH=/bin:/usr/bin:/usr/local/bin

# usage <status>
usage() {
    echo "usage: `basename "$0"` [-h] [file ...]" 1>&2
    exit $1
}

opt=
while getopts 'h' opt; do
    case $opt in
    h)      usage 0 ;;
    \?)     usage 1 ;;
    esac
done
shift `expr $OPTIND - 1`

exec sort -n ${@+"$@"} |
    uniq -c |
    sort -k 1 -n -r |
    awk 'NR == 1 { f = $1 } $1 != f { exit } { print }' |
    sort -k 2 -n
