#!/bin/sh
# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix
# @(#) Find a median value from text like seq(1).

set -u
umask 0022
IFS=$(printf ' \t\n_'); IFS=${IFS%_}
PATH=/bin:/usr/bin:/usr/local/bin
export IFS LC_ALL=C LANG=C PATH

readonly progname=${0##*/}
readonly version=1.1.0.20190407

# usage <exit-code>
usage() {
    echo "usage: $progname [-hv] [file ...]" 1>&2
    exit $1
}

# version (no parameter)
version() {
    echo "$progname $version" 1>&2
    exit 0
}

# main routine

opt=
while getopts 'hv' opt; do
    case $opt in
    h)      usage 0 ;;
    v)      version ;;
    \?)     usage 1 ;;
    esac
done
shift $(($OPTIND - 1))

exec sort -n ${@+"$@"} | awk '
{
    samples[NR] = $1
}
END {
    if (NR >= 1) {
        mid = int(NR / 2)
        print (NR%2 == 1) ? samples[mid+1] : (samples[mid] + samples[mid+1]) / 2
    }
}' ${@+"$@"}
